title: Advanced Business Solutions
logo: /assets/img/abs-logo.png
description: Business advisory services based on data science and artificial intelligence
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
